### ISSUE TITLE
Capacitor App.getLaunchUrl returns null

### ISSUE THREAD

**Issue by Nodonisko** [rdlabo/capacitor-facebook-login#10]
Capacitor API `App.getLaunchUrl` not working with this plugin, it always return null. I found that problem is in this code:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
		return SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
}
```
I am able to fix it by changing this to `return true` but I am not sure if it wont break anything. 

Thanks.

**Comment by rdlabo** [comment]
Mumu... It may be able to change this.

```
SDKApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
return true
```

I will try and check. Thanks.

**Comment by rdlabo** [comment]
I checked and update readme. Thanks for issues.
https://github.com/rdlabo/capacitor-facebook-login/commit/1b035abcc845a665a571fa7cf15eba1f78b70524
