### ISSUE TITLE
error: package jp.rdlabo.capacitor.plugin.facebook does not exist

### ISSUE THREAD

**Issue by matheusdavidson** [rdlabo/capacitor-facebook-login#11]
Hi, i'm getting this error when opening the project in Android Studio, i did all the config stated in README.md

**Comment by matheusdavidson** [comment]
i'm using 1.0.9 version

**Comment by matheusdavidson** [comment]
My environment:
```
Ionic:

   Ionic CLI                     : 5.0.3 (/Users/matheusdavidson/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 8.1.2
   @ionic/angular-toolkit        : 1.3.0

Capacitor:

   Capacitor CLI   : 1.1.1
   @capacitor/core : 1.1.1

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.6

System:

   NodeJS : v10.15.3 (/Users/matheusdavidson/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by rdlabo** [comment]
@matheusdavidson 

 Did you execute sync after npm install?

`$ npx cap sync`

**Comment by matheusdavidson** [comment]
yes, i did run sync command but still i couldn't see your package on Android Studio. I had to drag the plugin folder from node_modules(not the whole folder, only android folder content) to android studio

**Comment by rdlabo** [comment]
@matheusdavidson Please try it. https://github.com/rdlabo/capacitor-facebook-login-tutorial

You should not drag the plugin. If you go wrong somewhere, you can run the sync command.

![スクリーンショット 2019-08-04 9 59 07](https://user-images.githubusercontent.com/9690024/62418162-842adb80-b69e-11e9-926c-63bf9bc41bed.png)

**Comment by matheusdavidson** [comment]
Yeah, i know i'm not supposed to drag the plugin and do ```npx cap sync``` instead, but this didn't  place the plugin in android platform.

The only way i could make it work in android was manually doing what ```sync```does.

**Comment by matheusdavidson** [comment]
I will test with you repository to see if it behaves the same as here

**Comment by rdlabo** [comment]
@matheusdavidson Did you work? If you can't, please re-open this issue.
Thanks.

**Comment by acarolsf** [comment]
I have the same issue
