### ISSUE TITLE
Apple start to rejection apps with UIWebView

### ISSUE THREAD

**Issue by Nodonisko** [rdlabo/capacitor-facebook-login#12]
Hi,
Apple starts to rejecting apps with `UIWebView` API. We will need to upgrade to FB SDK for iOS 5.5.0 where is this problem fixed.

**Comment by rdlabo** [comment]
I forgot completely. Thank you for pointing out! I'm busy this week, so work is likely next week.

Thank you!

**Comment by Nodonisko** [comment]
@rdlabo Same for me, but maybe I will find some time to prep PR.

**Comment by LucasPMM** [comment]
@rdlabo Same error here. Please, fix this

**Comment by rdlabo** [comment]
@Nodonisko Finish prepare publish now!! I will try update this problem.

**Comment by rdlabo** [comment]
@Nodonisko @LucasPMM  `@rdlabo/capacitor-facebook-login@1.1.0-beta.5` is created. Please try it.

__it has some break change of `ios/App/App/AppDelegate.swift`__
Please see change log. 👉 https://github.com/rdlabo/capacitor-facebook-login/commit/5b0d4273d090b82ba7514495fdef95668e319da4

**Comment by rdlabo** [comment]
Released.
https://github.com/rdlabo/capacitor-facebook-login/releases/tag/1.1.0

**Comment by Nodonisko** [comment]
@rdlabo Great, thanks for fix!! 🎉

**Comment by rdlabo** [comment]
@Nodonisko Thanks check!!👍
