### ISSUE TITLE
Error on Android mainActivity.java

### ISSUE THREAD

**Issue by jcamposv** [rdlabo/capacitor-facebook-login#14]
I have this error when I init the plugin: error: package jp.rdlabo.capacitor.plugin.facebook does not exist do you know how can I fix it?

Thanks,
Jairo

**Comment by rdlabo** [comment]
You should restart Android Studio.

**Comment by jcamposv** [comment]
Hi @rdlabo thank you for your quick answer. I restarted Android Studio sometimes but didn't work.

Here is a small video about it: http://recordit.co/RqLheUbdkR

**Comment by rdlabo** [comment]
did you do `sync` ?  It seems not sync yet after install plugin.

**Comment by jcamposv** [comment]
yes, I did it but didn't work, do I need to add import into the file?

**Comment by rdlabo** [comment]
Sorry, I can't support. This isn't plugin issue.
If you did sync, Capacitor plugin display in Android Studio.(see image bottom). 
You may mistake step to using Capacitor plugin.

![スクリーンショット 2019-10-03 8 00 11](https://user-images.githubusercontent.com/9690024/66087846-deb7b980-e5b3-11e9-80a4-f0b95fb96475.png)

**Comment by rdlabo** [comment]
Maybe you can fix it with `rebuild project` , `clean project` or update capacitor version.

**Comment by jcamposv** [comment]
Hi @rdlabo thank you for your time!!, I fixed it running capacitor update
