### ISSUE TITLE
iOS project does not build

### ISSUE THREAD

**Issue by djabif** [rdlabo/capacitor-facebook-login#2]
Hi, thanks for doing this plugin. I can't get it to work on iOS 😰  (android works fine). My iOS project doesn't build when adding this plugin. I added everything your README says. It's a blank new ionic project with this plugin (I can share a repo if you want). Any hint about what can be happening? Thanks.
I'm using @ionic/angular 4.4.2, Capacitor 1.0 and latest version of Xcode

![Screen Shot 2019-05-24 at 10 34 14 AM](https://user-images.githubusercontent.com/1735814/58332639-03d03a80-7e12-11e9-891e-c40bab6d8ef4.png)

**Comment by rdlabo** [comment]
Thanks for create Issue. Did you add this line at `AppDelegate.swift`?

```diff
+ import FacebookCore
```

If FacebookCore is not found, you should run `npx cap update ios`.

**Comment by djabif** [comment]
Sure!

![Screen Shot 2019-05-24 at 11 17 08 AM](https://user-images.githubusercontent.com/1735814/58334242-84446a80-7e15-11e9-8663-13b22ec6b213.png)

**Comment by djabif** [comment]
Are you using Swift 4.2 or 5 ?

**Comment by rdlabo** [comment]
mumu... I tried now, and Capacitor 1.0.0 work well in my env.

`Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)`

```
Capacitor:
   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0
```

<img width="772" alt="スクリーンショット 2019-05-24 23 24 38" src="https://user-images.githubusercontent.com/9690024/58334882-60b40b00-7e7b-11e9-8c72-856047280c79.png">

**Comment by rdlabo** [comment]
And Xcode's version is 10.2.1.

**Comment by Nodonisko** [comment]
Same problem here, it works on local machine but not Bitrise CI... Both Xcode versions are 10.2.1 and capacitor 1.0

**Comment by djabif** [comment]
I'm using the same configs as yours but still getting the same error :( 
This is the repo I'm using to test https://github.com/djabif/capacitor-facebook-login-test

**Comment by rdlabo** [comment]
@djabif I could build at your repo. 

```sh
$ git clone git@github.com:djabif/capacitor-facebook-login-test.git
$ cd capacitor-facebook-login-test
$ npm i
$ ionic build
$ ionic cap update ios
$ $ ionic cap open ios
```

<img width="1402" alt="スクリーンショット 2019-05-25 8 45 34" src="https://user-images.githubusercontent.com/9690024/58361413-91229600-7ec9-11e9-864e-342f9d4a47f5.png">

It seems environment problem.  My env is here.

```
Ionic:

   Ionic CLI                     : 4.12.0 (/Users/sakakibara/dev/ionic-cli/packages/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.0.0
   @capacitor/core : 1.0.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.9.0
   OS     : macOS Mojave
```

and swift version is 5. Can you tell me your environment information?

**Comment by rdlabo** [comment]
It may not work on Swift 4.

https://stackoverflow.com/questions/43805987/unresolved-loginmanager-facebook-sdk-swift3?answertab=votes#tab-top

**Comment by rdlabo** [comment]
@djabif @Nodonisko @djabif  I found this stackoverflow. My plugin (using FacebookCore) may not work on Swift 4. Please try at Swift 5.

> Does not work in Swift 4. – Chewie The Chorkie May 3 '18 at 17:38

https://stackoverflow.com/questions/43805987/unresolved-loginmanager-facebook-sdk-swift3?answertab=votes#tab-top

**Comment by djabif** [comment]
Thank you so much @rdlabo for taking the time to check my repo. However, I can't get to build the project. I guess it should be something related to my environment which I can't figure out 😔. 
Anyway, I need a solution that works also for Swift 4 (because many people is still using it) so I think I will have build my own Capacitor plugin.

This is my env info and I'm also using Swift 5.

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   capacitor (Capacitor CLI) : 1.0.0
   @capacitor/core           : 1.0.0

System:

   NodeJS : v10.13.0 (/usr/local/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

I have `COCOAPODS: 1.7.0`

What I found strange is that in the versions of the Facebook libraries in the main `Podfile.lock` located in `ios/App/Podfile.lock `are different from the versions in the`Podfile.lock` from your module located in  `node_modules/@rdlabo/capacitor-facebook-login/ios/Plugin/Podfile.lock`. Maybe that can be a problem? I also found this https://github.com/facebook/facebook-swift-sdk/issues/458#issuecomment-495553904

**Comment by Nodonisko** [comment]
@rdlabo I also found there is forced Swift version 4.0 in your xcodeproj file.

**Comment by djabif** [comment]
It says 5.0 
https://github.com/djabif/capacitor-facebook-login-test/blob/5d7195fa12ab98bf89878514a687fd3ea503b862/ios/App/App.xcodeproj/project.pbxproj#L364

**Comment by Nodonisko** [comment]
@djabif That link to your repo you, probably changed that.

What about forcing pods version?
change this in plugin pod file
`
  pod 'FacebookCore'
  pod 'FacebookLogin'
`
to this
`
  pod 'FacebookCore', '~> 0.5.0'
  pod 'FacebookLogin', '~> 0.5.0'
`

version 0.5.0 should work with Swift 4

**Comment by Nodonisko** [comment]
I created PR that should solve issue.

**Comment by rdlabo** [comment]
Thanks for PR. @Nodonisko
marged and released ver 1.0.0.

**Comment by rdlabo** [comment]
@djabif @Nodonisko @djabif If it is possible, please install `@rdlabo/capacitor-facebook-login@1.0.0` and test at swift 4. Thanks.

**Comment by djabif** [comment]
Tried everything again with @rdlabo/capacitor-facebook-login@1.0.0 but the issue is still happening to me :( 
@Nodonisko did it work for you?

**Comment by Nodonisko** [comment]
@djabif Yea, it's working for me.

**Comment by rdlabo** [comment]
@djabif did you update capacitor/ios?
https://capacitor.ionicframework.com/docs/ios/updating#updating-capacitor-library

**Comment by Nodonisko** [comment]
@djabif Also try drop all xcode cache, or fresh clone repo to another folder... xcode caching lot of things

**Comment by alherrera42** [comment]
Hi! I have the exact same problem and tried with the latest plugin version (as of today) and Swift 4, on Xcode 10.1 (High Sierra). I actually realized most of the problems are just definitions (for example importing FBSDKLoginKit and then use `FBSDKLoginKit.LoginManager()` instead of `LoginManager()` ). The piece of code I got stuck is this: 

`let perm = permissions.map { ReadPermission.custom($0) }`
 
As I tried everything in this thread and the problem still goes on, is there a way that ReadPermission object can be mapped or defined from somewhere else like the FBSDK itself? If so, I can make a fork/pull request.

**Comment by jeremyaurelius** [comment]
Sorry folks. It does not work for me either. I have tried with `@capacitor/ios@1.0.0`, `@capacitor/ios@1.1.0`, swift 4, swift 4.2 and swift 5. Still nothing.

I investigated a little and it seems that Facebook itself describes its Swift SDK as "unstable" and recommends the use of its Objective-C SDK instead.
https://cocoapods.org/pods/FacebookLogin

**Comment by jeremyaurelius** [comment]
> Hi! I have the exact same problem and tried with the latest plugin version (as of today) and Swift 4, on Xcode 10.1 (High Sierra). I actually realized most of the problems are just definitions (for example importing FBSDKLoginKit and then use `FBSDKLoginKit.LoginManager()` instead of `LoginManager()` ). The piece of code I got stuck is this:
> 
> `let perm = permissions.map { ReadPermission.custom($0) }`
> 
> As I tried everything in this thread and the problem still goes on, is there a way that ReadPermission object can be mapped or defined from somewhere else like the FBSDK itself? If so, I can make a fork/pull request.

It seems that the `LoginManager` in FBSDKLoginKit has different method signatures to the one in `FacebookLogin`. Fortunately though, switching back to the old signature is easy, as permission is just a string array.

```
self.loginManager.logIn(permissions: permissions, from: self.bridge.viewController, handler: { (loginResult, error) in
}
```

**Comment by matheusdavidson** [comment]
I'm having exactly the same problem as @djabif, also tried his repository and it does not work for me either with these env:

```
Ionic:

   Ionic CLI                     : 5.0.3 (/Users/matheusdavidson/.nvm/versions/node/v10.15.3/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Capacitor:

   Capacitor CLI   : 1.1.0
   @capacitor/core : 1.1.0

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.6

System:

   NodeJS : v10.15.3 (/Users/matheusdavidson/.nvm/versions/node/v10.15.3/bin/node)
   npm    : 6.4.1
   OS     : macOS Mojave
```

**Comment by rdlabo** [comment]
Maybe fixed at latest.
https://github.com/rdlabo/capacitor-facebook-login/commit/80bb0e816c980889ee70bb3295ccb78de883823b#diff-1ac93e1d55d15f0b90dced740a2c9fdb

**Comment by matheusdavidson** [comment]
Could make it work with last release but i had to follow the new part of the README.md with a small change, here are the steps:

- Edit your ```ios/App/Podfile.lock```
- Replace all facebook pods for:
```
- FacebookCore (0.5.0):
    - Bolts (~> 1.9)
    - FBSDKCoreKit (~> 4.37)
  - FacebookLogin (0.5.0):
    - Bolts (~> 1.9)
    - FacebookCore (~> 0.5)
    - FBSDKCoreKit (~> 4.37)
    - FBSDKLoginKit (~> 4.37)
  - FBSDKCoreKit (4.37.0):
    - Bolts (~> 1.7)
  - FBSDKLoginKit (4.37.0):
    - FBSDKCoreKit
```
- run ```cd ios/App/App```
- run ```pod install```

**Comment by Nodonisko** [comment]
With latest version everything works well. Thanks!
