### ISSUE TITLE
FBSDKLog: Unable to obtain a key window,

### ISSUE THREAD

**Issue by pauldunn** [rdlabo/capacitor-facebook-login#28]
I have just created a new ionic and facebook apps but I get the following error when launching the IOS app:

`FBSDKLog: Unable to obtain a key window, marking <UIWindow: 0x7fa77a809e40; frame = (0 0; 414 896); hidden = YES; gestureRecognizers = <NSArray: 0x60000322d440>; layer = <UIWindowLayer: 0x600003c62740>> as keyWindow`

Any ideas how to fix this would be much appreciated.

Edit: please close this issue.  I thought it was causing the plugin not to work but the issue was elsewhere and the plugin is working fine.

**Comment by rdlabo** [comment]
> Edit: please close this issue.

Sure. Thanks.
