### ISSUE TITLE
Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'. [ng]   Types have separate declarations of a private property 'addWindowListener'.

### ISSUE THREAD

**Issue by addielmachado87** [rdlabo/capacitor-facebook-login#32]
Argument of type 'FacebookLoginWeb' is not assignable to parameter of type 'WebPlugin'.
[ng]   Types have separate declarations of a private property 'addWindowListener'.
registerWebPlugin(FacebookLogin);

import { registerWebPlugin } from '@capacitor/core';
import {  FacebookLogin } from '@rdlabo/capacitor-facebook-login';

registerWebPlugin(FacebookLogin);

**Comment by rdlabo** [comment]
Capacitor Plugin require same version to capacitor. so please update all capacitor npm package.
thanks.

**Comment by addielmachado87** [comment]
working fine  after update .thansk
