### ISSUE TITLE
Once I get the token how can I use it to actually get data about the user

### ISSUE THREAD

**Issue by Monomachus** [rdlabo/capacitor-facebook-login#4]
I manage to get accessToken and even userId (from getCurrentAccessToken() ), now how can I get real data about the user like his email and avatar? I've tried the interface Plugins.Facebook, but it seems like there's no implementation..

May be I'm getting it wrong, if so please advise on how to get data about the user.

**Comment by rdlabo** [comment]
@Monomachus  Sorry, I use https://github.com/facebook/php-graph-sdk in backend. (Send token from Frontend)
If you will development, I will review and marge. Thanks.

**Comment by Monomachus** [comment]
What I ended up doing is using the js sdk to get the data after I get the access token, something like this

```typescript
const FACEBOOK_GRAPHQL_NEEDED_FIELDS = ['name', 'first_name', 'last_name', 'email'];
declare let FB: any;

private getRegisterDataWith(fbToken: string) {
  if (fbToken) {
    console.log(`Facebook access token is ${fbToken}`);
    FB.api(`/me?fields=${FACEBOOK_GRAPHQL_NEEDED_FIELDS.join(',')}&access_token=${fbToken}`,
  	this.processFacebookGraphResponse.bind(this));
    this.hasAccessTokenSubject.next(true);
  }
  else {
    this.hasAccessTokenSubject.next(false);
  }
}

private async processFacebookGraphResponse(response: any) {

  if (response.error) {
    this.userRetrievedSuccessSubject.next(false);
  } else {
    response.picture = 'https://graph.facebook.com/' + response.id + '/picture?type=large';
  
    const fbUser = {
      name: response.name,
      firstName: response.first_name,
      lastName: response.last_name,
      email: response.email,
      picture: response.picture
    };
    
    await this.storage.set(FACEBOOK_USER, fbUser);
    this.userRetrievedSuccessSubject.next(true);
  }
}
```

Maybe it will help someone.

**Comment by densk1** [comment]
@Monomachus are you doing this client side? I'm trying this approach `FB.api('/me?...')` but getting an `Access-Control-Allow-Origin` error.

**Comment by Monomachus** [comment]
@densk1 had you indicated on Facebook the host you're trying to send data from? Like site URL or something like that for Facebook Login?

**Comment by densk1** [comment]
There was a config error on my part:
```
I had added `*.facebook.com` to the `"server": { "allowNavigation": ["*.facebook.com"] }` array in `capacitor.config.json`.
```

**Comment by drqwerty** [comment]
> ```ts
> FB.api(`/me?fields=${FACEBOOK_GRAPHQL_NEEDED_FIELDS.join(',')}&access_token=${fbToken}`,
>   	this.processFacebookGraphResponse.bind(this));
>     this.hasAccessTokenSubject.next(true);
> ```

For those looking for a promise version:

```ts
new Promise(resolve => {
  FB.api('/me', { fields: FACEBOOK_GRAPHQL_NEEDED_FIELDS.join(',') }, (userData) =>
    resolve(userData)
  );
}).then(response => this.processFacebookGraphResponse.bind(response));
```
