### ISSUE TITLE
Android build failing

### ISSUE THREAD

**Issue by Nodonisko** [rdlabo/capacitor-facebook-login#5]
Hi, 
I am having problem with this plugin and latest version of capacitor (1.1.0). It's throwing these errors:

`* What went wrong:
Execution failed for task ':rdlabo-capacitor-facebook-login:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  warn: removing resource jp.rdlabo.capacitor.plugin.facebook:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
  /Users/daniel/javascript/lymet/packages/self-care-mob-app/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/daniel/javascript/lymet/packages/self-care-mob-app/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/daniel/javascript/lymet/packages/self-care-mob-app/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values/values.xml:3974: error: resource android:attr/fontVariationSettings not found.
  /Users/daniel/javascript/lymet/packages/self-care-mob-app/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values/values.xml:3975: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
`

**Comment by rdlabo** [comment]
This is capacitor version Issue. I fixed by @rdlabo/capacitor-facebook-login@1.0.8
Please update.

**Comment by nstokoe** [comment]
This is still happening for me and I'm using version 1.0.8.

```* What went wrong:
Execution failed for task ':rdlabo-capacitor-facebook-login:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  warn: removing resource jp.rdlabo.capacitor.plugin.facebook:string/com_facebook_loginview_logged_in_using_facebook_f1gender without required default value.
  /builds/fullmeasure/product/front-ends/ui/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /builds/fullmeasure/product/front-ends/ui/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /builds/fullmeasure/product/front-ends/ui/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values/values.xml:3974: error: resource android:attr/fontVariationSettings not found.
  /builds/fullmeasure/product/front-ends/ui/node_modules/@rdlabo/capacitor-facebook-login/android/@rdlabo/capacitor-facebook-login/build/intermediates/res/merged/release/values/values.xml:3975: error: resource android:attr/ttcIndex not found.
  error: failed linking references.```

**Comment by Nodonisko** [comment]
For me still happening too @rdlabo
