### ISSUE TITLE
If I donate can you make a working example? 

### ISSUE THREAD

**Issue by travbus** [rdlabo/capacitor-facebook-login#7]
I'm new to capacitor and working with plugins. A example or video tutorial would be amazing. I would happily donate. I would like to create a simular plugin for fb accountKit. Thanks! I'll continue to try to get it to work.

**Comment by rdlabo** [comment]
@travbus Of course!! Because making example is not private benefit.
I will make example repository for capacitor-facebook-login tutorial of step by step.
(Sorry. I can't speak English well, so video is too dificult)

Thanks.

**Comment by travbus** [comment]
Awesome! Much appreciated! Though before you go through the trouble I may just try using the cordova plugin. 
https://github.com/wizcorp/phonegap-facebook-plugin
I never seen this plugin tell now.

**Comment by rdlabo** [comment]
@travbus  I created tutorial here!!!!
https://github.com/rdlabo/capacitor-facebook-login-tutorial

`phonegap-facebook-plugin` is great plugin. But in capacitor, this have some trouble. So I created this plugin.

**Comment by travbus** [comment]
Thanks I"ll give it ago. I'll see if I am able to change the angular stuff to vue.

**Comment by travbus** [comment]
Thanks for making that tutorial I got the plugin to work with vue.js I posted example here if someone asks
https://github.com/travbus/capacitor-vue-example

**Comment by rdlabo** [comment]
> I got the plugin to work with vue.js

Great!! I am glad that I could be helpful to you!😁

**Comment by rdlabo** [comment]
@travbus Thanks for donate. This is first donate I got at OSS!
